### PR TITLE
Adding a pv and wind-powered electrical heater with molten salt TES

### PR DESCRIPTION
**Pull request by arfontalvoANU**
The test for the WindPVsaltTESsystem is running successfully with dummy inputs.

### CODE REVIEW

**Comment by jdpipe** [comment]
HeaterControl.mo seems to be unused, maybe can  be removed?
In HotPumpControl, perhaps we can add some labelling on the variables that have no description/explanation, like L_mea?
Consider clearer names of 'm_flow' (hot pump flow rate, will supply the demand) and 'm_flow_in' (the flow rate of hot salt into the tank, used to limit the outlet flow when the tank is low).
ScheduleLogic.mo would benefit from some annotation to describe what its purpose is, how it works.
Consider, where appropriate, basing new models on suitable base models from MSL, eg Boiler.mo?

In GridInput.mo, spelling on 'CurtaimentPower'.
Change name of on_pv.
Document the meaning of state_con == 1 and state_con == 2. It is 'on' and 'off' 
Change Q to P, indicating electrical power.
Force the renewable output to zero in case where on_pv is false.
Consider combining state_con and on_pv into a single discrete variable.
Review variable naming, avoid variable names that differ only in case/punct. P_renew_out instead of ReneawbleInput?
Consider a naming convention that use VARTYPE_specification, eg P_in, T_hot, 45Q_in, table_pv, etc.
pv_ref should perhaps be pv_file or file_pv or something instead.
The idea of a RenewableGenerator base model, and wind and pv as refinements of that -- but this can be later work!

Consider adding cost equations for components. Consider adding something generic.

Maybe we need to modify postproc.py (?) to work with systems with a heat output (LCOH or something).

**Comment by jdpipe** [comment]
looks like your test is failing on the test server, armando:
```
 self = <test_wind_pv_salt_tes_system.TestScheduler testMethod=test_sched>

    def test_sched(self):
    	# Note these are set to the values for what is thought to be a working
    	# version.  They are not validated against anything or independently
    	# calculated.
    	ref_annual_ouput = 273744.99056518177 # Reference annnual thermal output
    	annual_output=self.mat.data('E_thermal')[-1]
    	annual_output = annual_output/(1e6*3600) # Convert from J/year to MWh/year
    	# Testing output
>   	self.assertTrue(abs(annual_output- ref_annual_ouput)/ref_annual_ouput<0.01)
E    AssertionError: False is not true
```

**Comment by arfontalvoANU** [comment]
> looks like your test is failing on the test server, armando:
> 
> ```
>  self = <test_wind_pv_salt_tes_system.TestScheduler testMethod=test_sched>
> 
>     def test_sched(self):
>     	# Note these are set to the values for what is thought to be a working
>     	# version.  They are not validated against anything or independently
>     	# calculated.
>     	ref_annual_ouput = 273744.99056518177 # Reference annual thermal output
>     	annual_output=self.mat.data('E_thermal')[-1]
>     	annual_output = annual_output/(1e6*3600) # Convert from J/year to MWh/year
>     	# Testing output
> >   	self.assertTrue(abs(annual_output- ref_annual_ouput)/ref_annual_ouput<0.01)
> E    AssertionError: False is not true
> ```

I addressed the comments and improved the documentation. The test is failing due to the new constraints in the grid input, i.e., stopping the power supply when the input is below a user-defined threshold. I also increased the heater efficiency to 99%, which is the same heater efficiency value as the tank heaters.

**Comment by jdpipe** [comment]
seems to be passing now!

**Pull request merged**
